name: inspirations
favicon: null
layout_spectrum: 0.5291496918071061
typography_spectrum: 0.20057245390489697
title: 'Inspiration - Sharing Eureka, Brainwave and Brainstorm moments'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121413'
    - '#304e20'
    - '#948d8f'
    - '#b7afb2'
    - '#689856'
  brandStrength: 0.5
  lightness: 0.8996375524438918
  saturation: 0.8989994311705232
  rhythmicContrast: 0.43692658212967217
purpose: []
